In [60]:
import pandas as pd

In [61]:
# read the data
education = pd.read_excel('../data/Education Obstacle - opening.xlsx', header=None)
education.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,Note: there are more sheets in this document,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Each session is found on its own sheet below. ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Date,Session,Voter,"If you want to change the world, throw a bette...",Welcome to the Obstacle Courses!:,:,Where are you calling from?: x,Where are you calling from?: y,I (choose all that apply):: 1,I (choose all that apply):: 2,I (choose all that apply):: 3,"When you hear ""thriving education ecosystems"",...","When you hear ""thriving education ecosystems"",...","When you hear ""thriving education ecosystems"",...","When you hear ""thriving education ecosystems"",...",Finally – today would you rather::
3,2023-06-19,1,1,NaN,NaN,NaN,NaN,NaN,run a network,am part of a movement,NaN,communities connected in a shared vision of le...,young people visible and audible as holders of...,Intergenerational conversations,Love,Tell Stories
4,2023-06-19,1,2,NaN,NaN,NaN,0.5599,0.2855,am part of a movement,run a network,support networks,"Learning ecosystem that is relevant, adaptable...",NaN,NaN,NaN,Dance

# Data Cleaning

In [62]:
# deleting the first two rows
education = education.iloc[2:]

In [63]:
# assigning new header
new_header = education.iloc[0]
education = education[1:]
education.columns = new_header

education = education.reset_index(drop=True)
education.head()

2,Date,Session,Voter,"If you want to change the world, throw a better party!:",Welcome to the Obstacle Courses!:,:,Where are you calling from?: x,Where are you calling from?: y,I (choose all that apply):: 1,I (choose all that apply):: 2,I (choose all that apply):: 3,"When you hear ""thriving education ecosystems"", what comes to mind?: 1","When you hear ""thriving education ecosystems"", what comes to mind?: 2","When you hear ""thriving education ecosystems"", what comes to mind?: 3","When you hear ""thriving education ecosystems"", what comes to mind?: 4",Finally – today would you rather::
0,2023-06-19,1,1,NaN,NaN,NaN,NaN,NaN,run a network,am part of a movement,NaN,communities connected in a shared vision of le...,young people visible and audible as holders of...,Intergenerational conversations,Love,Tell Stories
1,2023-06-19,1,2,NaN,NaN,NaN,0.5599,0.2855,am part of a movement,run a network,support networks,"Learning ecosystem that is relevant, adaptable...",NaN,NaN,NaN,Dance
2,2023-06-19,1,3,NaN,NaN,NaN,0.4325,0.1551,support networks,NaN,NaN,Repetition,NaN,NaN,NaN,NaN
3,2023-06-19,1,4,NaN,NaN,NaN,0.5054,0.3263,am a donor,NaN,NaN,Educational stakeholders have strong relations...,NaN,NaN,NaN,Tell Stories
4,2023-06-19,1,5,NaN,NaN,NaN,0.0604,0.4089,something else,NaN,NaN,"a system that has the person at the center, he...",NaN,NaN,NaN,Tell Stories

## Renaming the category columns

In [64]:
# renaming the columns
education = education.rename(columns={'I (choose all that apply):: 1': 'first_category'})
education = education.rename(columns={'I (choose all that apply):: 2': 'second_category'})
education = education.rename(columns={'I (choose all that apply):: 3': 'third_category'})

In [65]:
education.head()

2,Date,Session,Voter,"If you want to change the world, throw a better party!:",Welcome to the Obstacle Courses!:,:,Where are you calling from?: x,Where are you calling from?: y,first_category,second_category,third_category,"When you hear ""thriving education ecosystems"", what comes to mind?: 1","When you hear ""thriving education ecosystems"", what comes to mind?: 2","When you hear ""thriving education ecosystems"", what comes to mind?: 3","When you hear ""thriving education ecosystems"", what comes to mind?: 4",Finally – today would you rather::
0,2023-06-19,1,1,NaN,NaN,NaN,NaN,NaN,run a network,am part of a movement,NaN,communities connected in a shared vision of le...,young people visible and audible as holders of...,Intergenerational conversations,Love,Tell Stories
1,2023-06-19,1,2,NaN,NaN,NaN,0.5599,0.2855,am part of a movement,run a network,support networks,"Learning ecosystem that is relevant, adaptable...",NaN,NaN,NaN,Dance
2,2023-06-19,1,3,NaN,NaN,NaN,0.4325,0.1551,support networks,NaN,NaN,Repetition,NaN,NaN,NaN,NaN
3,2023-06-19,1,4,NaN,NaN,NaN,0.5054,0.3263,am a donor,NaN,NaN,Educational stakeholders have strong relations...,NaN,NaN,NaN,Tell Stories
4,2023-06-19,1,5,NaN,NaN,NaN,0.0604,0.4089,something else,NaN,NaN,"a system that has the person at the center, he...",NaN,NaN,NaN,Tell Stories

## Renaming the opinion columns

In [66]:
education = education.rename(columns={'When you hear "thriving education ecosystems", what comes to mind?: 1': 'thriving_ecosystems_1'})
education = education.rename(columns={'When you hear "thriving education ecosystems", what comes to mind?: 2': 'thriving_ecosystems_2'})
education = education.rename(columns={'When you hear "thriving education ecosystems", what comes to mind?: 3': 'thriving_ecosystems_3'})
education = education.rename(columns={'When you hear "thriving education ecosystems", what comes to mind?: 4': 'thriving_ecosystems_4'})

In [67]:
education.head()

2,Date,Session,Voter,"If you want to change the world, throw a better party!:",Welcome to the Obstacle Courses!:,:,Where are you calling from?: x,Where are you calling from?: y,first_category,second_category,third_category,thriving_ecosystems_1,thriving_ecosystems_2,thriving_ecosystems_3,thriving_ecosystems_4,Finally – today would you rather::
0,2023-06-19,1,1,NaN,NaN,NaN,NaN,NaN,run a network,am part of a movement,NaN,communities connected in a shared vision of le...,young people visible and audible as holders of...,Intergenerational conversations,Love,Tell Stories
1,2023-06-19,1,2,NaN,NaN,NaN,0.5599,0.2855,am part of a movement,run a network,support networks,"Learning ecosystem that is relevant, adaptable...",NaN,NaN,NaN,Dance
2,2023-06-19,1,3,NaN,NaN,NaN,0.4325,0.1551,support networks,NaN,NaN,Repetition,NaN,NaN,NaN,NaN
3,2023-06-19,1,4,NaN,NaN,NaN,0.5054,0.3263,am a donor,NaN,NaN,Educational stakeholders have strong relations...,NaN,NaN,NaN,Tell Stories
4,2023-06-19,1,5,NaN,NaN,NaN,0.0604,0.4089,something else,NaN,NaN,"a system that has the person at the center, he...",NaN,NaN,NaN,Tell Stories

## Choosing only the Required Columns

In [68]:
# choosing only the needed columns
education_clean = education[['first_category', 'second_category', 'third_category', 'thriving_ecosystems_1', 'thriving_ecosystems_2', 'thriving_ecosystems_3', 'thriving_ecosystems_4']]

In [69]:
education_clean.head()

2,first_category,second_category,third_category,thriving_ecosystems_1,thriving_ecosystems_2,thriving_ecosystems_3,thriving_ecosystems_4
0,run a network,am part of a movement,NaN,communities connected in a shared vision of le...,young people visible and audible as holders of...,Intergenerational conversations,Love
1,am part of a movement,run a network,support networks,"Learning ecosystem that is relevant, adaptable...",NaN,NaN,NaN
2,support networks,NaN,NaN,Repetition,NaN,NaN,NaN
3,am a donor,NaN,NaN,Educational stakeholders have strong relations...,NaN,NaN,NaN
4,something else,NaN,NaN,"a system that has the person at the center, he...",NaN,NaN,NaN

In [70]:
len(education_clean)

17

# Grouping by First Category

In [71]:
# grouping by the first category
first_category = education_clean.groupby('first_category')
for group, group_data in first_category: 
    print("Group: ", group)
    print("Group data: ", group_data)
    print("\n")

Group:  am a donor
Group data:  2 first_category second_category third_category  \
3     am a donor             NaN            NaN

2                              thriving_ecosystems_1 thriving_ecosystems_2  \
3  Educational stakeholders have strong relations...                   NaN

2 thriving_ecosystems_3 thriving_ecosystems_4
3                   NaN                   NaN


Group:  am part of a movement
Group data:  2          first_category second_category    third_category  \
1   am part of a movement   run a network  support networks
13  am part of a movement  something else               NaN
14  am part of a movement             NaN               NaN

2                               thriving_ecosystems_1 thriving_ecosystems_2  \
1   Learning ecosystem that is relevant, adaptable...                   NaN
13                                      Collaboration              Holistic
14     System-wide change and working in partnerships                   NaN

2  thriving_ecosystems_3 thriving_ecosystems_4
1                    NaN                   NaN
13                   NaN                   NaN
14                   NaN                   NaN


Group:  run a network
Group data:  2  first_category        second_category third_category  \
0   run a network  am part of a movement            NaN
5   run a network  am part of a movement            NaN
6   run a network                    NaN            NaN
9   run a network                    NaN            NaN
10  run a network                    NaN            NaN

2                               thriving_ecosystems_1  \
0   communities connected in a shared vision of le...
5                       Systems Thinking in Education
6   interconnected spaces that include families + ...
9                                      Systems change
10                                      Collaboration

2                               thriving_ecosystems_2  \
0   young people visible and audible as holders of...
5                       Theory of Change in Education
6                                                 NaN
9                           Quality education for all
10                                  Holistic Outcomes

2             thriving_ecosystems_3 thriving_ecosystems_4
0   Intergenerational conversations                  Love
5       Interconnecting in learning       Empathy Mapping
6                               NaN                   NaN
9                            Access                   NaN
10                           Equity                   NaN


Group:  something else
Group data:  2   first_category second_category third_category  \
4   something else             NaN            NaN
11  something else   run a network            NaN

2                               thriving_ecosystems_1 thriving_ecosystems_2  \
4   a system that has the person at the center, he...                   NaN
11  I imagine decentralised, context-aware solutio...                   NaN

2  thriving_ecosystems_3 thriving_ecosystems_4
4                    NaN                   NaN
11                   NaN                   NaN


Group:  support networks
Group data:  2     first_category        second_category third_category  \
2   support networks                    NaN            NaN
8   support networks  am part of a movement            NaN
12  support networks             am a donor            NaN
16  support networks          run a network            NaN

2                               thriving_ecosystems_1  \
2                                          Repetition
8   All stakeholders that contribute to learning t...
12                                                Joy
16                                                NaN

2     thriving_ecosystems_2 thriving_ecosystems_3 thriving_ecosystems_4
2                       NaN                   NaN                   NaN
8                       NaN                   NaN                   NaN
12  equitable opportunities                   NaN                   NaN
16                      NaN                   NaN                   NaN

In [72]:
donors = first_category.get_group('am a donor')
donors.head()

2,first_category,second_category,third_category,thriving_ecosystems_1,thriving_ecosystems_2,thriving_ecosystems_3,thriving_ecosystems_4
3,am a donor,NaN,NaN,Educational stakeholders have strong relations...,NaN,NaN,NaN

In [73]:
movement = first_category.get_group('am part of a movement')
movement.head()

2,first_category,second_category,third_category,thriving_ecosystems_1,thriving_ecosystems_2,thriving_ecosystems_3,thriving_ecosystems_4
1,am part of a movement,run a network,support networks,"Learning ecosystem that is relevant, adaptable...",NaN,NaN,NaN
13,am part of a movement,something else,NaN,Collaboration,Holistic,NaN,NaN
14,am part of a movement,NaN,NaN,System-wide change and working in partnerships,NaN,NaN,NaN